### ISSUE TITLE
extra parameters are always null

### ISSUE THREAD

**Issue by sooryaraj** [jiusanzhou/flutter_notification_listener#1]
```
  void onData(NotificationEvent event) {
    print(event.toString());
    print(event.extra); // here return null
  }
```

**Comment by jiusanzhou** [comment]
@sooryaraj The `extra` field need to be **DEPRECATED**, every fields in the `event` are all coming from `notification.extras` except `packageName` and `timestamp`. You can check the code in [NotificationEvent.kt#L26](https://github.com/jiusanzhou/flutter_notification_listener/blob/master/android/src/main/kotlin/im/zoe/labs/flutter_notification_listener/NotificationEvent.kt#L26) and [event.dart#L27](https://github.com/jiusanzhou/flutter_notification_listener/blob/master/lib/src/event.dart#L27).

Feel free to fork and modify those code for what you want.
