### ISSUE TITLE
Terminate in Android 10

### ISSUE THREAD

**Issue by sadiq61651** [jiusanzhou/flutter_notification_listener#11]
A new issue which a face with this plugin is that it doesn't work continuously in background in Android 10 after sometime system by default terminate it and it stop listening the incoming notifications...

Hope so u help me to sort out this issue 
thank u

**Comment by jiusanzhou** [comment]
Do you have start the service foreground, which will send a notification? 
Maybe this is not 100% warrant to avoid this situation, because of the Adnroid power safer strategy. If you still have troubles, try to find and disable battery safer(mostly in the system settings), or you can just make the app's activity foreground.

**Comment by sadiq61651** [comment]
Did u have Facebook id i want to communicate u there.

**Comment by jiusanzhou** [comment]
Sorry, I don't use the Facebook messenger usually. If you have any questions you can comment at here, and other people can give advice.

**Comment by sadiq61651** [comment]
Look i try it in Huawei, infinix, and oppo phone and it terminate it after
sometime...
I use autostart flutter pkg also but it's not working...

**Comment by jiusanzhou** [comment]
Do you have start the service foreground, which will send a notification?

And how long does the app keep running?
If less than hours maybe there are some other issues.

Can you try the method mentioned in https://dontkillmyapp.com/oppo which make the system trying not to kill the app. Try this method if you can and testing if it works.

**Comment by jiusanzhou** [comment]
Hey, this issue having no updates for 1 month, I will close it. If you have any problem please open a new issue, thank you.
