### ISSUE TITLE
Multiple Notifications

### ISSUE THREAD

**Issue by akhilgorantala** [jiusanzhou/flutter_notification_listener#12]
Actually the problem is when a notification update and adds a new line to the notification. It is showing the data multiple times. Is it possible to show only the updated notification.

Example: 
Notification:
Hello my name is Akhil
Updated Notification 1:
Hello my name is Shiva
Hello my name is Akhil
Updated Notification 2:
Hello my name is zoe
Hello my name is Shiva
Hello my name is Akhil

is it possible to show only the first line every time, without repeating the 2,3.. lines.

**Comment by jiusanzhou** [comment]
Hi @akhilgorantala , IMO the android notifications only show the current state, that means this plugin takes `the real` content of notifications.

If you want the diff cotent, I think you should do it the your own code, not the plugin one.
I have released the v1.1.0 which added the notification id field.
So you can use `packageName` and `id` to unique the notifaction, and compare the content with the old one while getting a updated notifaction.

**Comment by Zaman0070** [comment]
i also face the same issue

**Comment by Zaman0070** [comment]
dear if anyone have any suitable solution then please tell me

**Comment by ZiaUrRahmam** [comment]
@jiusanzhou you can use the solution provided by @jiusanzhou 

> If you want the diff cotent, I think you should do it the your own code, not the plugin one.
I have released the v1.1.1 version which added the notification id field.
So you can use packageName and id to unique the notifaction, and compare the content with the old one while getting a updated notifaction.

first of all store the incoming notifications somewhere like for example in a list of  type NotificationEvent.
the you have to check 
`bool doesExists;
for(var x in list){
if(x.id == new_notification_event.id){
doesExists = true;
break;
}else{
doesExists = false;
}
}`

and you can use doesExists as reference for whether the notification is repeated or new one.

its just a sample you can optimize this or can used according to your needs.

**Comment by jiusanzhou** [comment]
You can try a map for cache the events.

```dart

  Map<String, Map<int, NotificationEvent>> eventsCache = {};

  void onData(NotificationEvent event) {
    if (eventsCache[event.packageName] == null) eventsCache[event.packageName] = {};
    // get the old event
    var old = eventsCache[event.packageName][event.id];
    // store the new one
    eventsCache[event.packageName][event.id] = event;


    var myevent = event;

    // try to take diff content
    if (old != null) {
      // diff logic, simple diff just replace
      // fit your own need
      myevent.text = myevent.text.replaceAll(old.text+"\n", "");
    }

    print(myevent.toString());
}
```

**Comment by akhilgorantala** [comment]
Actually this is happenning in this type of notification
![WhatsApp Image 2022-05-04 at 4 29 48 PM](https://user-images.githubusercontent.com/75612659/166669891-9d41efa1-8fe3-497b-8454-d69ee726007e.jpeg)
![WhatsApp Image 2022-05-04 at 4 29 49 PM](https://user-images.githubusercontent.com/75612659/166669897-ea61a22d-d39a-4aee-aca4-abe1c93afd41.jpeg)
![WhatsApp Image 2022-05-04 at 4 29 49 PM (1)](https://user-images.githubusercontent.com/75612659/166669905-98dd0897-c3b3-4d17-9168-09bf041dfceb.jpeg)
![WhatsApp Image 2022-05-04 at 4 29 50 PM](https://user-images.githubusercontent.com/75612659/166669909-2b56f2aa-ca4c-45a9-bb49-a38210997cff.jpeg)

i tried to debug it but i didnt find what causing this.

**Comment by ZiaUrRahmam** [comment]
> So you can use `packageName` and `id` to unique the notifaction, and compare the content with the old one while getting a updated notifaction.

@jiusanzhou  does this id is unique for every incoming message or not ?

**Comment by akhilgorantala** [comment]
> > So you can use `packageName` and `id` to unique the notifaction, and compare the content with the old one while getting a updated notifaction.
> 
> @jiusanzhou  does this id is unique for every incoming message or not ?

For every app it has a unique I'd.

**Comment by ZiaUrRahmam** [comment]
> For every app it has a unique I'd.

If its as it then
If @jiusanzhou somehow if you may add an id for every incoming notification then it would be so great that we can even get which msg has been deleted after sent.
It would be a game changing feature.

Nd @jiusanzhou i request you to share a method through which we can support your work as buy me a coffe etc.
It would be honor for me to work with u
Thanks in advance.

**Comment by akhilgorantala** [comment]
> > For every app it has a unique I'd.
> 
> If its as it then If @jiusanzhou somehow if you may add an id for every incoming notification then it would be so great that we can even get which msg has been deleted after sent. It would be a game changing feature.
> 
> Nd @jiusanzhou i request you to share a method through which we can support your work as buy me a coffe etc. It would be honor for me to work with u Thanks in advance.


Edit - every app notification channel has its own id.

**Comment by jiusanzhou** [comment]
The `channelId` of notifaction requires the sdk >= `26`, so I did't add this field to event, but as @akhilgorantala  says, different channels in the same app can have the same ids.
Maybe using the `packageName`, `channelId` and `id` to unique
the notification is correct.

So there are 2 solutions:
1. exports `packageName`, `channelId` and `id` fields from native android, currently only `packageName` and `id`,  should add `channelId`
2. export a `unique_id` field which generated from `packageName`, `channelId` and `id` by hash function in the plugin, so `unique_id`field is not a original one, maybe cause some confuse for others

I need some advice from  you guys, which one we should use?

**Comment by ZiaUrRahmam** [comment]
> So there are 2 solutions:\n\nexports packageName, channelId and id fields from native android, currently only packageName and id, should add channelId\nexport a unique_id field which generated from packageName, channelId and id by hash function in the plugin, so unique_idfield is not a original one, maybe cause some confuse for others

I didn't get the point.

Do you planning
1. to assign a unique id to each channel
2.Or to assign a unique id to each notification

**Comment by akhilgorantala** [comment]
> Actually this is happenning in this type of notification
> ![WhatsApp Image 2022-05-04 at 4 29 48 PM](https://user-images.githubusercontent.com/75612659/166669891-9d41efa1-8fe3-497b-8454-d69ee726007e.jpeg)
> ![WhatsApp Image 2022-05-04 at 4 29 49 PM](https://user-images.githubusercontent.com/75612659/166669897-ea61a22d-d39a-4aee-aca4-abe1c93afd41.jpeg)
> ![WhatsApp Image 2022-05-04 at 4 29 49 PM (1)](https://user-images.githubusercontent.com/75612659/166669905-98dd0897-c3b3-4d17-9168-09bf041dfceb.jpeg)
> ![WhatsApp Image 2022-05-04 at 4 29 50 PM](https://user-images.githubusercontent.com/75612659/166669909-2b56f2aa-ca4c-45a9-bb49-a38210997cff.jpeg)
> 
> i tried to debug it but i didnt find what causing this.

We can't fix this issue even if we do this thing u said @jiusanzhou because the single notification is repeating for this type of notifications.

**Comment by ZiaUrRahmam** [comment]
> We can't fix this issue even if we do this thing u said @jiusanzhou because the single notification is repeating for this type of notifications.

I have fixed it by rectifying notifications.
the part that @jiusanzhou  mentioned is also necessry for many other operations.
And i dont know how you are implimenting the logic. Please show the code part then may be able to help in this specific case.

**Comment by jiusanzhou** [comment]
These are 2 different issues, the previous discussion was how to ensure uniqueness of notifications.

> We can't fix this issue even if we do this thing u said @jiusanzhou because the single notification is repeating for this type of notifications.

What is your real problem? Is that only 1 notifications on the phone status pannel, but we got multi notification from the plugin?

**Comment by akhilgorantala** [comment]
@jiusanzhou yes single notification, but it is always repeating 2 times when a new notification arrives.
check the screenshots
![WhatsApp Image 2022-05-05 at 1 31 43 PM](https://user-images.githubusercontent.com/75612659/166884526-5b0e4176-594e-40e9-b22c-2a72751792bb.jpeg)
![WhatsApp Image 2022-05-05 at 1 31 42 PM](https://user-images.githubusercontent.com/75612659/166884539-c2adb5fe-65d1-438c-86d2-3d10a1681664.jpeg)

**Comment by akhilgorantala** [comment]
@ZiaUrRahmam can u explain in detail so i can help u out with code.

**Comment by ZiaUrRahmam** [comment]
> @ZiaUrRahmam can u explain in detail so i can help u out with code.

I am able to get filtered notifications means we can get rid of duplicates

**Comment by jiusanzhou** [comment]
> yes single notification, but it is always repeating 2 times when a new notification arrives.

I get it. In fact some application will update one  notification for multiple times. You can check `timestamp` field which takeen from android object `StatusBarNotification`. If not same that means we did receive multiple notifications (actually is update operations).
What do I know so far, whatsapp will send twice (create once and update once).
That will call the `onNotificationPosted` for multiple times, this is the mechanism of the android's notification listen service.

You can open the logcat to confirm and see what happened. Tips: use `send notification event` keywords for filter

**Comment by akhilgorantala** [comment]
it has some milli seconds difference, in this case what we need to do @jiusanzhou

**Comment by akhilgorantala** [comment]
> > @ZiaUrRahmam can u explain in detail so i can help u out with code.
> 
> I am able to get filtered notifications means we can get rid of duplicates

can u explain how u did it ?

**Comment by jiusanzhou** [comment]
I have release the `v1.2.0` and add the `uniqueId` field which generated from `StatusBarNotification.key` if sdk > 20. Please try it and confirm this can fix you guys' problems.
For all fields please check https://github.com/jiusanzhou/flutter_notification_listener#object-notificationevent

**Comment by akhilgorantala** [comment]
@ZiaUrRahmam can u please tell me how you fixed the duplicate notification.

**Comment by jiusanzhou** [comment]
> @jiusanzhou can u please explain how to get a single notification, i tried round the double value to int (time stamp) but it has some milli seconds gap. Sometimes it is getting 26, 27 and sometimes the both values are same. can u suggest me any good fix.

Choose a method according to your situation:
- use `uniqueId` to deduplicate: *in some case, although only milli seconds gap, but them are different notification. At most time, their actions is not same, this is necessary to implement the auto reply.*
- use `packageName`, `channelId` and `id` to deduplicate, as what you see is what you get.

**Comment by akhilgorantala** [comment]
@jiusanzhou I'd is same for multiple notification, but i don't know how to make it a single notification ? Can u please give me some example.
