### ISSUE TITLE
FATAL EXCEPTION: main java.lang.IllegalArgumentException: 

### ISSUE THREAD

**Issue by ZiaUrRahmam** [jiusanzhou/flutter_notification_listener#13]
@jiusanzhou first of all thank you ❤ for these fast releases for fixing the previous issues. I want you to support this package because its background activity makes it one above all of all the plugins of its category and for this I wanna congratulate you for your efforts and this amazing package and urgent basis support and  its upgradation .

 I just tested the plugin . when a new notification arrives it shuts down the app and shows the following exception.

`D/NotificationsListenerService( 6880): send event to flutter side immediately!
D/NotificationsListenerService( 6880): send notification event: {infoText=null, showWhen=true, largeIcon=android.graphics.Bitmap@2be619b, package_name=com.whatsapp, text=Khair Mubarak, id=1, title=Uzair, subText=null, timestamp=1651594571082}
D/AndroidRuntime( 6880): Shutting down VM
E/AndroidRuntime( 6880): FATAL EXCEPTION: main
E/AndroidRuntime( 6880): Process: com.example.notifilistener, PID: 6880
E/AndroidRuntime( 6880): java.lang.IllegalArgumentException: Unsupported value: 'android.graphics.Bitmap@2be619b' of type 'class android.graphics.Bitmap'
E/AndroidRuntime( 6880): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:292)
E/AndroidRuntime( 6880): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:280)
E/AndroidRuntime( 6880): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:272)
E/AndroidRuntime( 6880): 	at io.flutter.plugin.common.StandardMethodCodec.encodeMethodCall(StandardMethodCodec.java:38)
E/AndroidRuntime( 6880): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:120)
E/AndroidRuntime( 6880): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:104)
E/AndroidRuntime( 6880): 	at im.zoe.labs.flutter_notification_listener.NotificationsHandlerService.sendEvent(NotificationsHandlerService.kt:343)
E/AndroidRuntime( 6880): 	at im.zoe.labs.flutter_notification_listener.NotificationsHandlerService.onNotificationPosted$lambda-4$lambda-3(NotificationsHandlerService.kt:119)
E/AndroidRuntime( 6880): 	at im.zoe.labs.flutter_notification_listener.NotificationsHandlerService.lambda$wTcveBaq1Mksq9Jc43eX7rDkbc0(Unknown Source:0)
E/AndroidRuntime( 6880): 	at im.zoe.labs.flutter_notification_listener.-$$Lambda$NotificationsHandlerService$wTcveBaq1Mksq9Jc43eX7rDkbc0.run(Unknown Source:4)
E/AndroidRuntime( 6880): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime( 6880): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 6880): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime( 6880): 	at android.app.ActivityThread.main(ActivityThread.java:6819)
E/AndroidRuntime( 6880): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6880): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:497)
E/AndroidRuntime( 6880): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:912)
Lost connection to device.
Exited (sigterm)`

After then app stops and after a small period of time, it again reboots.

**Comment by jiusanzhou** [comment]
Thank you for your testing and the exception information helped me.
I add some logic to support for `largeIcon`, maybe some app use `Bitmap` not the `Icon`, which cause this crash. I will fix this ASAP.

**Comment by jiusanzhou** [comment]
@ZiaUrRahmam , I have fixed in `v1.1.2`, but I can't  product such a notifaction with bitmap as large icon in whatsapp, so I can not test if these works fine.

BTW I add `try exception`, so it's wont crash the service if any type not supported.

**Comment by ZiaUrRahmam** [comment]
> BTW I add try exception, so it's wont crash the service if any type not supported.

I'll chech it today and i hope it gets solved.
Thanku for immediate support

**Comment by ZiaUrRahmam** [comment]
@jiusanzhou  its working fine. Am checking it further. Btw thanks for your efforts.
