### ISSUE TITLE
MissingPluginException 

### ISSUE THREAD

**Issue by ZiaUrRahmam** [jiusanzhou/flutter_notification_listener#14]
I am trying to save the notifications  using pathprovider and sqflite packages
when the are capture from static callback method. 
But it is not allowing me to do so because of the following exception:
`
MissingPluginException(MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider))`

actually this is happening because the path_provider package is not registered for background activity.

**Previously** I was working with [https://github.com/ekasetiawans/flutter_background_service](https://github.com/ekasetiawans/flutter_background_service) and I faced the same issue the i used the solution provided [here](https://github.com/ekasetiawans/flutter_background_service/issues/138)  but when i switched to yours package and tested now the after using even this solution its still showing the same exception.

please have a look into it and help  me solve it.
I'll be providing more info when required.

**Related github discussions and solution on this topic:**
[https://github.com/fluttercommunity/flutter_workmanager/issues/6](https://github.com/fluttercommunity/flutter_workmanager/issues/6)
[MissingPluginException when using external plugins (SharedPreferences, PathProvider, etc)](https://github.com/ekasetiawans/flutter_background_service/issues/138)

**Comment by lel101** [comment]
@ZiaUrRahmam when you add DartPluginRegistrant.ensureInitialized();, does the exception change ?

**Comment by ZiaUrRahmam** [comment]
> @ZiaUrRahmam when you add DartPluginRegistrant.ensureInitialized();, does the exception change ?

I have used following code snippet
```
if (Platform.isIOS) YourPluginIOS.registerWith(); if (Platform.isAndroid) YourPluginAndroid.registerWith();
```

**Comment by lel101** [comment]
@ZiaUrRahmam 

> DartPluginRegistrant.ensureInitialized();,
You need to change your channel to beta and DartPluginRegistrant is already created. But I already tried it but instead another error occur.

**Comment by jiusanzhou** [comment]
Try these steps first:
1. `flutter clean`
2. `flutter pub get`
3. `flutter run` or restart the debug app.

**Comment by lel101** [comment]
@jiusanzhou still not working.

`Exception has occurred.
PlatformException (PlatformException(channel-error, Unable to establish connection on channel., null, null))
`

**Comment by jiusanzhou** [comment]
@ZiaUrRahmam  `flutter_notification_listener` use 2 kind of the flutter engine:
1. open the main app to start activity
2. start the engine by service after reboot, entrypoint is the static function your registered

If this exception happens when the first situation, that maybe the common problem in flutter, at most time `flutter clean` & `flutter run` will be helpul.

The second one, you should make sure other plugins are initialized in the static function.

**Comment by ZiaUrRahmam** [comment]
> 2\. start the engine by service after reboot, the dartExecutor's entrypoint is the static function your registered

the 2nd method solved my issue and now its working fine.
@jiusanzhou Thank you very much.

@lel101 Instead of using beta version use flutter stable and it will get solved when you register following in static calback function.

> I have used following code snippet
> 
> ```
> if (Platform.isIOS) YourPluginIOS.registerWith(); 
> if (Platform.isAndroid) YourPluginAndroid.registerWith();
> ```

**Comment by akhilgorantala** [comment]
@ZiaUrRahmam can u please tell me how to use only the data single time, it is repeating every time. am trying to send the data only single time to an api.
![Screenshot 2022-05-06 152150](https://user-images.githubusercontent.com/75612659/167111382-f01e0c50-084b-48de-a878-6bdfcd95d278.png)

![Screenshot 2022-05-06 150909](https://user-images.githubusercontent.com/75612659/167111377-24bbf959-9457-4739-82ea-acde5da3ef65.png)
![Screenshot 2022-05-06 152627](https://user-images.githubusercontent.com/75612659/167111386-21b6ca82-9437-45f7-85c3-98f63e1457de.png)

**Comment by ZiaUrRahmam** [comment]
@akhilgorantala  please don't ask here as you already have opened a new issue for your question.
This thread has been solved and sepecific for missing plugin exception.
thanks

**Comment by lel101** [comment]
@ZiaUrRahmam thank you,  btw does it work inside flutter_background_service ?
> static void _callback(NotificationEvent event) {
    if (Platform.isAndroid) PathProviderAndroid.registerWith();
    if (Platform.isAndroid) YourPluginAndroid.registerWith();
    print("send evt to ui: $evt");
    final SendPort? send = IsolateNameServer.lookupPortByName("_listener_");
    if (send == null) print("can't find the sender");
    send?.send(event);
  }

**Comment by ZiaUrRahmam** [comment]
@lel101  yes its working. Give it a try. and let us know if it did not work.
**Note**
Please use flutter stable version.

**Comment by ZiaUrRahmam** [comment]
@lel101 you have to register your shared preferences in calback function

**Comment by jiusanzhou** [comment]
Hey, this issue having no updates for 1 month, I will close it. If you have any problem please open a new issue, thank you.
