### ISSUE TITLE
Foreground notification not getting stopped 

### ISSUE THREAD

**Issue by ZiaUrRahmam** [jiusanzhou/flutter_notification_listener#16]
@jiusanzhou here i am referring the  [previous thread](https://github.com/jiusanzhou/flutter_notification_listener/issues/9 ) 
 where we were working on and that was closed but i still found the issue there.
Passing false to foreground service 
Is working but when the app starts for the first time then forgreground notification shows up even though i am using

await NotificationsListener.startService(foreground: false);

but when we stop and then again start the service then its starts working as expected with out notification.

****Feature Request****
Also if you may add a function to check whether the service is in foreground or background then it would be a great feature.

**Comment by ZiaUrRahmam** [comment]
@jiusanzhou any updates?

**Comment by jiusanzhou** [comment]
this problem has been fixed in the release `v1.3.1`, you can have a try.

**Comment by jiusanzhou** [comment]
@ZiaUrRahmam hey, dis this works for you?

**Comment by ZiaUrRahmam** [comment]
@jiusanzhou  yes it worked perfectly.
and also I found another issue that is not related to this one .
I will be discussing it with you by tomorrow after confirming the behaviour.
