### ISSUE TITLE
v1.3.1 build fails

### ISSUE THREAD

**Issue by jonny7737** [jiusanzhou/flutter_notification_listener#17]
Build console reports the following type and null safety issues:

`
e: /Users/jonny/dev-tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_notification_listener-1.3.1/android/src/main/kotlin/im/zoe/labs/flutter_notification_listener/FlutterNotificationListenerPlugin.kt: (179, 30): Type mismatch: inferred type is Long? but Long was expected

e: /Users/jonny/dev-tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_notification_listener-1.3.1/android/src/main/kotlin/im/zoe/labs/flutter_notification_listener/FlutterNotificationListenerPlugin.kt: (200, 39): Type mismatch: inferred type is Long? but Long was expected

e: /Users/jonny/dev-tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_notification_listener-1.3.1/android/src/main/kotlin/im/zoe/labs/flutter_notification_listener/NotificationsHandlerService.kt: (64, 25): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ArrayList<CapturedType(*)>?

e: /Users/jonny/dev-tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_notification_listener-1.3.1/android/src/main/kotlin/im/zoe/labs/flutter_notification_listener/NotificationsHandlerService.kt: (71, 25): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ArrayList<CapturedType(*)>?

e: /Users/jonny/dev-tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_notification_listener-1.3.1/android/src/main/kotlin/im/zoe/labs/flutter_notification_listener/NotificationsHandlerService.kt: (72, 25): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ArrayList<CapturedType(*)>?

e: /Users/jonny/dev-tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_notification_listener-1.3.1/android/src/main/kotlin/im/zoe/labs/flutter_notification_listener/NotificationsHandlerService.kt: (79, 25): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ArrayList<CapturedType(*)>?

e: /Users/jonny/dev-tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_notification_listener-1.3.1/android/src/main/kotlin/im/zoe/labs/flutter_notification_listener/NotificationsHandlerService.kt: (80, 25): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ArrayList<CapturedType(*)>?

e: /Users/jonny/dev-tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_notification_listener-1.3.1/android/src/main/kotlin/im/zoe/labs/flutter_notification_listener/NotificationsHandlerService.kt: (81, 26): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ArrayList<CapturedType(*)>?

e: /Users/jonny/dev-tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_notification_listener-1.3.1/android/src/main/kotlin/im/zoe/labs/flutter_notification_listener/NotificationsHandlerService.kt: (86, 25): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ArrayList<CapturedType(*)>?

FAILURE: Build failed with an exception.
`

Any help moving forward would be greatly appreciated.

--Jonny

**Comment by jiusanzhou** [comment]
hi Jonny, I'm not sure what the problem is, it's no problem for me, can you provide your version of Kotlin.

**Comment by jonny7737** [comment]
Kotlin-Version: 1.6
Implementation-Version: 1.6.21-release-334

**Comment by jiusanzhou** [comment]
Can you directly use Android Studio to open the android directory in the example, and build in AS, let AS check errors automatically.

**Comment by jonny7737** [comment]
I downloaded the package source and opened the example project in AS.  Run results in the same errors as before.

`
e: /Users/jonny/StudioProjects/flutter_notification_listener-master/android/src/main/kotlin/im/zoe/labs/flutter_notification_listener/FlutterNotificationListenerPlugin.kt: (179, 30): Type mismatch: inferred type is Long? but Long was expected
e: /Users/jonny/StudioProjects/flutter_notification_listener-master/android/src/main/kotlin/im/zoe/labs/flutter_notification_listener/FlutterNotificationListenerPlugin.kt: (200, 39): Type mismatch: inferred type is Long? but Long was expected
e: /Users/jonny/StudioProjects/flutter_notification_listener-master/android/src/main/kotlin/im/zoe/labs/flutter_notification_listener/NotificationsHandlerService.kt: (64, 25): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ArrayList<CapturedType(*)>?
e: /Users/jonny/StudioProjects/flutter_notification_listener-master/android/src/main/kotlin/im/zoe/labs/flutter_notification_listener/NotificationsHandlerService.kt: (71, 25): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ArrayList<CapturedType(*)>?
e: /Users/jonny/StudioProjects/flutter_notification_listener-master/android/src/main/kotlin/im/zoe/labs/flutter_notification_listener/NotificationsHandlerService.kt: (72, 25): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ArrayList<CapturedType(*)>?
e: /Users/jonny/StudioProjects/flutter_notification_listener-master/android/src/main/kotlin/im/zoe/labs/flutter_notification_listener/NotificationsHandlerService.kt: (79, 25): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ArrayList<CapturedType(*)>?
e: /Users/jonny/StudioProjects/flutter_notification_listener-master/android/src/main/kotlin/im/zoe/labs/flutter_notification_listener/NotificationsHandlerService.kt: (80, 25): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ArrayList<CapturedType(*)>?
e: /Users/jonny/StudioProjects/flutter_notification_listener-master/android/src/main/kotlin/im/zoe/labs/flutter_notification_listener/NotificationsHandlerService.kt: (81, 26): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ArrayList<CapturedType(*)>?
e: /Users/jonny/StudioProjects/flutter_notification_listener-master/android/src/main/kotlin/im/zoe/labs/flutter_notification_listener/NotificationsHandlerService.kt: (86, 25): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ArrayList<CapturedType(*)>?

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_notification_listener:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
`

**Comment by jonny7737** [comment]
Are you using Flutter 3?

**Comment by jiusanzhou** [comment]
No, flutter 2.

I add non-null asserted based on the error lines in the log, please checkout the [type-check-error](https://github.com/jiusanzhou/flutter_notification_listener/tree/hotfix/type-check-error) branch, and try to build it again

**Comment by jonny7737** [comment]
Better :^)

`
e: /Users/jonny/StudioProjects/flutter_notification_listener-hotfix-type-check-error/android/src/main/kotlin/im/zoe/labs/flutter_notification_listener/NotificationsHandlerService.kt: (64, 25): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ArrayList<CapturedType(*)>?
e: /Users/jonny/StudioProjects/flutter_notification_listener-hotfix-type-check-error/android/src/main/kotlin/im/zoe/labs/flutter_notification_listener/NotificationsHandlerService.kt: (71, 25): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ArrayList<CapturedType(*)>?
e: /Users/jonny/StudioProjects/flutter_notification_listener-hotfix-type-check-error/android/src/main/kotlin/im/zoe/labs/flutter_notification_listener/NotificationsHandlerService.kt: (72, 25): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ArrayList<CapturedType(*)>?
e: /Users/jonny/StudioProjects/flutter_notification_listener-hotfix-type-check-error/android/src/main/kotlin/im/zoe/labs/flutter_notification_listener/NotificationsHandlerService.kt: (79, 25): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ArrayList<CapturedType(*)>?
e: /Users/jonny/StudioProjects/flutter_notification_listener-hotfix-type-check-error/android/src/main/kotlin/im/zoe/labs/flutter_notification_listener/NotificationsHandlerService.kt: (80, 25): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ArrayList<CapturedType(*)>?
e: /Users/jonny/StudioProjects/flutter_notification_listener-hotfix-type-check-error/android/src/main/kotlin/im/zoe/labs/flutter_notification_listener/NotificationsHandlerService.kt: (81, 26): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ArrayList<CapturedType(*)>?
e: /Users/jonny/StudioProjects/flutter_notification_listener-hotfix-type-check-error/android/src/main/kotlin/im/zoe/labs/flutter_notification_listener/NotificationsHandlerService.kt: (86, 25): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ArrayList<CapturedType(*)>?

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_notification_listener:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction

`

**Comment by jiusanzhou** [comment]
please update the branch and retry.

**Comment by jonny7737** [comment]
Compiles and runs.  

The example app interface seems to function on my physical device but no output is displayed.

Thanks.

**Comment by jiusanzhou** [comment]
Ok, i will relase this hotfix to a new version `v1.3.2`.
