### ISSUE TITLE
When app closed from recent apps menu, notification listener stops working

### ISSUE THREAD

**Issue by dapperappdeveloper** [jiusanzhou/flutter_notification_listener#18]
Error:
```
D/NotificationsListenerService( 6374): send event to flutter side immediately!
D/NotificationsListenerService( 6374): send notification event: {infoText=null, canTap=true,...}
W/FlutterJNI( 6374): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: flutter_notification_listener/bg_method. Response ID: 11
```

As the title says, when the app is closed from the recent app menu, and a notification is posted, it seems like the listener has a broken channel connection and the dart code does not run, and produces the error message ` Could not send. Channel: flutter_notification_listener/bg_method`
If the app is open, `onData` runs fine

Any help/discussion would be greatly appreciated :)

The code:
```dart
void onData(NotificationEvent event) async {
  print("NOTIFICATION");
  print(event.toString());
}

void _callback(NotificationEvent evt) {
  print("send evt to ui: $evt");
  final SendPort? send = IsolateNameServer.lookupPortByName("_listener_");
  if (send == null) print("can't find the sender");
  send?.send(evt);
}

Future<void> initNotificationListener() async {
  ReceivePort port = ReceivePort();

  NotificationsListener.initialize(callbackHandle: _callback);
  NotificationsListener.registerEventHandle(_callback);

  IsolateNameServer.removePortNameMapping("_listener_");
  IsolateNameServer.registerPortWithName(port.sendPort, "_listener_");
  port.listen((message) => onData(message));
}

Future<bool> startListening() async {
  print("start listening");
  bool? hasPermission = await NotificationsListener.hasPermission;
  if (hasPermission == null || hasPermission == false) {
    print("no permission, so open settings");
    NotificationsListener.openPermissionSettings();
  }

  bool? isRunning = await NotificationsListener.isRunning;

  if (isRunning != null && isRunning == false) {
    await NotificationsListener.startService();
  }

  return true;
}
```

```dart
void main() async {
  await initNotificationListener();
  await startListening();
}
```

**Comment by jiusanzhou** [comment]
Hi @dapperappdeveloper, thank you for your detailed description.

When the app closed, the flutter engine which handing events exits also. The question is that should be to start an engine for the new events? At some time, maybe user want to stop completely, otherwise the app will become evil.

If we want to support handing events while app is not running, we can start a headless flutter engine to process. Actually, the plugin did this after rebooting.

I'm not sure should we need to support this feature, any discussion are welcome!

**Comment by smurat** [comment]
Hi @jiusanzhou .Iif is it possible, I think this feature would be very useful.

**Comment by cbenhagen** [comment]
@jiusanzhou I also think you should start an engine in this case. Otherwise our application might miss some important events. I think it's in the responsibility of the app using this plugin to allow enabling or disabling this functionality. In any case, a user can always remove the permission to get notifications or uninstall the app completely.

**Comment by sadiq61651** [comment]
I am facing the same issue any possible solution?

**Comment by vmwsree** [comment]
I am trying to post the notification data firebase even when the app is not running, Is there a way to do it without the flutter engine? currently, my HTTP calls are not happening even when I am using the example app

`Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: flutter_notification_listener/bg_method. Response ID: 16`

I get this log on my console when a notification hits and the app is not running. but I can see the app has force stop active showing its in the memory

**Comment by jiusanzhou** [comment]
Hi @vmwsree , currently we must start a flutter engine first to handle the notification in flutter side. I have implemented stating one while engine is not running, if it doesn't work, maybe some bug in there.

**Comment by jaanonim** [comment]
I need this feature. It will be great if you can implement or give me a work around.

**Comment by dhruvpatidar359** [comment]
hi @jiusanzhou , if you have the path to how to implement this ,please tell i will try to make it work . As i need this soo much.

**Comment by Droyder7** [comment]
Hi all, I have raised a fix for this issue. Please have a look : https://github.com/jiusanzhou/flutter_notification_listener/pull/46

**Comment by Jace-Joji** [comment]
@jiusanzhou How to fix this issue? I need it too
