### ISSUE TITLE
Geting java.lang.IllegalArgumentException: Unsupported value: [Ljava.lang.CharSequence;@2c4fe0d

### ISSUE THREAD

**Issue by sanjib292-cmd** [jiusanzhou/flutter_notification_listener#2]
When i try To run Example code From this package On notification I got java.lang.IllegalArgumentException: Unsupported value: [Ljava.lang.CharSequence;@2c4fe0d what could be the issue? How to fix!

**Comment by jiusanzhou** [comment]
Hi, thank you for pay attention to this plugin. 

Would you mind to provide more logs from Logcat? 
Maybe be there some lines contains key information about which line code cause this Exception.

**Comment by sanjib292-cmd** [comment]
> Hi, thank you for pay attention to this plugin.
> 
> Would you mind to provide more logs from Logcat?
> Maybe be there some lines contains key information about which line code cause this Exception.

when there is any notification from whatsapp or youtube than it shut down itself

**Comment by jiusanzhou** [comment]
@sanjib292-cmd san I have fixed the exception, and tested with whatsapp. You can update to v1.0.6.
Feel free to reopen the issue if you have any promble about this.
