### ISSUE TITLE
Example project not working on release mode (Android)

### ISSUE THREAD

**Issue by ys-li** [jiusanzhou/flutter_notification_listener#24]
Thank you for this amazing plugin - however I have some problem working with it on release mode. `flutter run --release` on the example project and my project.

When I was trying to listen to the notification with a static callback function through the service launched by the app, this is logged:

>I/flutter (13345): Service is not already running
I/flutter (13345): start listening
I/flutter (13345): no permission, so open settings
I/flutter (13345): start listening
I/flutter (13345): stop listening
I/flutter (13345): start listening
E/flutter (13345): [ERROR:flutter/shell/common/shell.cc(93)] Dart Error: Class '_NotificationsLogState' not found in library ''.
E/flutter (13345): [ERROR:flutter/shell/common/shell.cc(93)] Dart Error: Class '_NotificationsLogState' not found in library ''.
E/flutter (13345): [ERROR:flutter/shell/common/shell.cc(93)] Dart Error: Class '_NotificationsLogState' not found in library ''.
E/flutter (13345): [ERROR:flutter/shell/common/shell.cc(93)] Dart Error: Class '_NotificationsLogState' not found in library ''.
E/flutter (13345): [ERROR:flutter/shell/common/shell.cc(93)] Dart Error: Class '_NotificationsLogState' not found in library ''.
E/flutter (13345): [ERROR:flutter/shell/common/shell.cc(93)] Dart Error: Class '_NotificationsLogState' not found in library ''.

I suspect this is due to the service not being able to access the class where the static callback is located. Any help would be appreaciated. Thanks!

Flutter doctor:
>Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.8, on Microsoft Windows [Version 10.0.19044.2130], locale en-HK)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.5.4)
[!] Android Studio (version 4.0)
    ✗ Unable to determine bundled Java version.
[✓] VS Code (version 1.73.0)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

**Comment by jiusanzhou** [comment]
@ys-li Hi, try to use flutter 2.x , I think maybe there are some limitation in the flutter 3.x, and the code don't fit it.

**Comment by ys-li** [comment]
I digged around a little and found similar problem in another plugin:
[https://github.com/ekasetiawans/flutter_background_service/issues/246](url)

Adding the `@pragma('vm:entry-point')` annotation to the static function in the example project fixes the issue.
Feel free to verify, thanks!

**Comment by jiusanzhou** [comment]
Hi @ys-li that's great, thank you for your PR.

**Comment by echo-LuGuang** [comment]
```
@pragma('vm:entry-point')  //<--打包必须添加这个属性，我觉得插件说明里有必要强调一下
  static void _callback(NotificationEvent evt) {
    debugPrint(evt.toString());
    Fluttertoast.showToast(
      msg: evt.text!,
      toastLength: Toast.LENGTH_SHORT,
    );

```
