### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by mobiletoly** [jiusanzhou/flutter_notification_listener#37]
Hi. We are getting these exception in crashlytics:

Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
im.zoe.labs.flutter_notification_listener.NotificationEvent$Companion.getActions (NotificationEvent.kt:159)
im.zoe.labs.flutter_notification_listener.NotificationEvent$Companion.fromSbn (NotificationEvent.kt:75)
im.zoe.labs.flutter_notification_listener.NotificationEvent.<init> (NotificationEvent.kt:18)
im.zoe.labs.flutter_notification_listener.NotificationsHandlerService.onNotificationRemoved (NotificationsHandlerService.kt:170)
android.service.notification.NotificationListenerService.onNotificationRemoved (NotificationListenerService.java:501)
android.service.notification.NotificationListenerService.onNotificationRemoved (NotificationListenerService.java:527)
android.service.notification.NotificationListenerService.onNotificationRemoved (NotificationListenerService.java:539)
android.service.notification.NotificationListenerService$MyHandler.handleMessage (NotificationListenerService.java:2362)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loopOnce (Looper.java:226)
android.os.Looper.loop (Looper.java:313)
android.app.ActivityThread.main (ActivityThread.java:8762)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:604)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1067)

**Comment by mobiletoly** [comment]
I created this pull request, could you please merge it?

https://github.com/jiusanzhou/flutter_notification_listener/pull/38

**Comment by jiusanzhou** [comment]
great, Thank you for your PR.

**Comment by mobiletoly** [comment]
thank you! any plans for a new release any time soon?

**Comment by jiusanzhou** [comment]
@mobiletoly  Already published to v1.3.3 , please take a look.
