### ISSUE TITLE
[Question] Keep the listener active without having to display the listener notification

### ISSUE THREAD

**Issue by jesselpereira** [jiusanzhou/flutter_notification_listener#47]
Hey there! Thank you so much for maintaining this much needed and powerful dependency.

I have a question: Can I keep the listener active even with the app closed and without needing to display the listener notification?

It would be a hassle to keep the notification pinned forever.

I appreciate your work, thank you for everything.

**Comment by Droyder7** [comment]
You can try starting the listener service with foreground parameter as false to not show any foreground service notification, but this may not guarantee the service will be alive in the background for all the time, as android may kill the services with no active foreground services running for battery saving or other purposes. 

But you can try it, it should work in most of the cases.
