### ISSUE TITLE
Kotlin Gradle plugin version 1.5.20 and higher.

### ISSUE THREAD

**Issue by Vali5681** [jiusanzhou/flutter_notification_listener#48]
Hello!

On One UI 6.0 and Android 14 I am getting, recently, this error:

`* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':flutter_notification_listener' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
Exception: Gradle task assembleDebug failed with exit code 1`

What could it be done to solve this error, generally?

**Comment by Vali5681** [comment]
I was facing this in flutter_notification_listener v1.3.3.

Apparently, it should be fixed since this commit: https://github.com/jiusanzhou/flutter_notification_listener/commit/d1921100f7f0717d8601644ba550f2ae4b21886b

When will a new pub package version be released?

**Comment by jiusanzhou** [comment]
> When will a new pub package version be released?

Hi @Vali5681 I have published a new version `1.3.4`, please take a look.

**Comment by Vali5681** [comment]
Thank you! The issue can be closed.
