### ISSUE TITLE
"_callback" EventCallbackFunc is not called even if notification is triggered.

### ISSUE THREAD

**Issue by midgetfx** [jiusanzhou/flutter_notification_listener#5]
I'd tried to adapt to my project code. but EventCallbackFunc is not called.
I've imported "flutter_notification_listener: ^1.0.7".

Following is running log.
```
D/NOTIFICATION_PLUGIN(22798): install callback dispatch ...
I/flutter (22798): Service is not aleary running
D/NOTIFICATION_PLUGIN(22798): store the promote args ...
D/NotificationsListenerService(22798): on call start listener service
D/NotificationsListenerService(22798): get the lock
D/NotificationsListenerService(22798): ok let's init
I/NotificationsListenerService(22798): create flutter engine
I/NOTIFICATION_PLUGIN(22798): on attached to engine
I/NOTIFICATION_PLUGIN(22798): attached engine finished
D/NotificationsListenerService(22798): init finished
D/NotificationsListenerService(22798): service initialized
```
According to the log, NotificationsLisnenerService is started and connected between flutter and android.
But, even if any notification is triggered, custom EventCallbackFunc is not called.

Following is my sample code.
```dart
 static void _callback(NotificationEvent evt) {
    print("send evt to ui: $evt");
    var send = IsolateNameServer.lookupPortByName(SERVICE_NAME);
    if (send == null) print("can't find the sender");
    send?.send(evt);
  }

  Future<bool?> initPlatformState() async {
    await NotificationsListener.initialize(callbackHandle: _callback);

    IsolateNameServer.removePortNameMapping(SERVICE_NAME);
    IsolateNameServer.registerPortWithName(port.sendPort, SERVICE_NAME);
    port.listen((message) => onData(message));

    var isR = await NotificationsListener.isRunning;
    print("""Service is ${!isR! ? "not " : ""}aleary running""");
    return isR;
  }
```

**Comment by jiusanzhou** [comment]
Hi, did you see any log(debug level) like "send notification event xxx" which print in the native android,when your notification triggered?

If didn't,maybe error occurred while parse the notification in native code.

Would you mind to provide App name which produced the notification.

**Comment by midgetfx** [comment]
Well, no, that log is not occurred.
It worked fine at first, but it doesn't work now after repeated start/stop the app during debugging.

```dart
Connecting to VM Service at ws://127.0.0.1:52393/mNQgG_FFcG8=/ws
D/NOTIFICATION_PLUGIN(  538): install callback dispatch ...
I/flutter (  538): Service is not aleary running
D/NotificationsListenerService(  538): init finished
D/NotificationsListenerService(  538): service initialized
D/ViewRootImpl@de87ec6[MainActivity](  538): ViewPostImeInputStage processPointer 0
W/System  (  538): ClassLoader referenced unknown path: /system/framework/QPerformance.jar
E/BoostFramework(  538): BoostFramework() : Exception_1 = java.lang.ClassNotFoundException: Didn't find class "com.qualcomm.qti.Performance" on path: DexPathList[[],nativeLibraryDirectories=[/system/lib, /vendor/lib]]
V/BoostFramework(  538): BoostFramework() : mPerf = null
D/ViewRootImpl@de87ec6[MainActivity](  538): ViewPostImeInputStage processPointer 1
```

I cannot tell you about the app name because notification is triggered in my app with "flutter_local_notifications: ^8.1.1+2" library. And, my app is designed with the cubic of "flutter_bloc: ^7.2.0".
So, let me tell you my app structure.

NotificationListener of "flutter_notification_listener: ^1.0.7" and NotificationService of "flutter_local_notifications: ^8.1.1+2" are created in the main function of main.dart and provided by BlocProvider of "flutter_bloc: ^7.2.0".

```dart 
void main() async {
  int serviceID = 0;
  NotificationsListenService listenService =
      NotificationsListenService(serviceID++);

  NotificationAppLaunchDetails? notificationAppLaunchDetails =
      await initNotificationService();

  String channelId = "NotificationService id";
  String channelName = "NotificationService  name";
  String channelDescription = "NotificationService  description";

  NotificationService notificationService = NotificationService(serviceID++,
      notificationAppLaunchDetails, channelId, channelName, channelDescription);

  runApp(MultiBlocProvider(
    providers: [
      BlocProvider<NotificationsListenService>(
          create: (context) => listenService),
      BlocProvider<NotificationService>(
          create: (context) => notificationService),
    ],
    child: MyApp(),
  ));
}
```

When main page is constructed and initState is called, notification listener is initialized as your guide.
```dart
@override
  void initState() {
    BlocProvider.of<NotificationsListenService>(context)
        .initPlatformState()
        .then((value) async {
      await BlocProvider.of<NotificationsListenService>(context)
          .startListening();
    });
    super.initState();
  }
```

When these codes are performed, The permission request screen appears correctly.
But if I make a notification by "flutter_local_notifications: ^8.1.1+2", I couldn't see any response.
Thanks for your kind.

**Comment by jiusanzhou** [comment]
So for late.
I had tested the `flutter_local_notifications ` in own device and everything work fine.
I thank maybe you have some trouble in creating the notifaction.

**Comment by midgetfx** [comment]
Thanks for the response.
Also, I've debugged and checked the log. 
First I tested in the old device and notification listener service (android side) was not showing received notification message. I guess notification service might be unregistered in android os. After that, I've tested at another device and I've checked everything work fine. So I think this is platform issue related to android os version. Thank you.

I have one question.
I hope to receive every notifications and handle them in the flutter side. And I checked my app is handling the notification in the foreground. But if I killed the app in the history such as releasing memory, I couldn't receive anything. When I launch the app again, everything is ok. So would you guide me how to stay notification listener and handing service is working in backgound?

Thanks for your kindness.

**Comment by jiusanzhou** [comment]
Currently the plugin doesn't support keep the service alive with force kill. As the Android, swiping up in the task center will force kill the service.

What pass the tests is exiting the app as normal, the service will keep running. If you want to keep the service living for more long time, you can add the app to while list in the power management.

Unfortunately, I'm not every familiar with keeping alive the android service. 
So, waiting for a pr to improve

**Comment by midgetfx** [comment]
Thanks a lot. This is not a issue. So i will close it. Thanks
