### ISSUE TITLE
Notifications not getting detected

### ISSUE THREAD

**Issue by sumanbaul** [jiusanzhou/flutter_notification_listener#6]
Instagram notifications not getting detected.
While testing on a lower version Android 7, it was not able to detect any notifications.

**Comment by jiusanzhou** [comment]
hi @sumanbaul, that's exactly there are some apis calling required the android up than Oreo(android 8). Maybe that's why this plugin doesn't work in android 7.

I don't have a android 7 device, so there is not chance to debugging and improve these.

Thank you for your attention.
