### ISSUE TITLE
Replying to the notification

### ISSUE THREAD

**Issue by MarceloRab** [jiusanzhou/flutter_notification_listener#7]
Could you add the possibility to respond to the notification and have access to the audio attached to the notification? I have a smartwatch and I would like to build an app for these functions.

See here java methods for this function. [HERE](https://lowcarbrob.medium.com/how-to-reply-to-android-app-notifications-c09e44da9bdb)

**Comment by jiusanzhou** [comment]
Hi @MarceloRab, Sorry for the late reply.

These would be great features:
- interactive notification in flutter side
- audio access(maybe as a audio file to flutter side)

I will spend time researching theme when I have time. Thank you!

**Comment by MarceloRab** [comment]
Thank you very much for your attention. Looking forward to these features.

**Comment by X-SLAYER** [comment]
I have created a similar package for notifications listening and u can use it to reply to notifications
you can take a look here [notification_listener_service](https://pub.dev/packages/notification_listener_service)

**Comment by jiusanzhou** [comment]
I have released v1.2.0 to support interactive notification.
