### ISSUE TITLE
Background working 

### ISSUE THREAD

**Issue by ZiaUrRahmam** [jiusanzhou/flutter_notification_listener#8]
Hey @jiusanzhou hope you are well.
I am curious if this plugin still works automatically after the device gets rebooted.?

**Comment by jiusanzhou** [comment]
Hi @ZiaUrRahmam,
I had tried to implement starting the service automatically after reboot. 
But I haven't tested if it works well.

**Comment by ZiaUrRahmam** [comment]
@jiusanzhou  is there any way that we can impliment this functionality using some background service packages.
I have tried with one but the other package starts showing error.
It would be great if you  through some light on this.
I have used this package [flutter_background_service](https://pub.dev/packages/flutter_background_service)

**Comment by jiusanzhou** [comment]
@ZiaUrRahmam Hi, I have fix the bug in auto starting after reboot, if you have any problems please track the issue #10. And I will close this issue.
