### ISSUE TITLE
can we stop showing foreground service notification from notification panel

### ISSUE THREAD

**Issue by ZiaUrRahmam** [jiusanzhou/flutter_notification_listener#9]
hey @jiusanzhou  I want to hide the "service is running" foreground notification from notification panel.
Also what should I do to change this notification's icon, title and subtitle;

**Comment by jiusanzhou** [comment]
We can change notifactoin's title, subtitle and description, but the icon taken from app's icon resource, can't modify it for now.  If you want to chang them, just add params when you calling `startService`:
```dart
NotificationsListener.startService(
          title: "Listener Running",
          subTitle: "I'm subtitle",
          description: "Let's scrape the notifactions...");
```

If you want to disable the foreground notifaction, use `foreground: false`,
```dart
NotificationsListener.startService(
          foreground: false,
);
```

All params `startService` supported like below,
```dart
startService({
    bool foreground = true,
    String subTitle = "",
    bool showWhen = false,
    String title = "Notification Listener",
    String description = "Service is running",
  })
```

**Comment by ZiaUrRahmam** [comment]
```
startService({
    bool foreground = false
    String subTitle = "",
    bool showWhen = false,
    String title = "Notification Listener",
    String description = "Service is running",
  })
```
its not working. When i set these params foreground notification continues to show

**Comment by jiusanzhou** [comment]
I just tested again, it works fine. 

You should clean the service or uninstall the app before change the code, that means with hot-reloading in flutter  won't clean the notifaction which alreally exists.

**Comment by jiusanzhou** [comment]
Hi @ZiaUrRahmam , I will close this issue, if you have any problem, feel free to open it again

**Comment by ZiaUrRahmam** [comment]
@jiusanzhou  yes it working but when the app starts for the first time then forgreound notification shows up even though i am using
>await NotificationsListener.startService(foreground: false);

but when we  stop and then again start the service then its starts working as expected with out niotification.
